### ISSUE TITLE
Header is not mobile/narrow-browser friendly

### ISSUE THREAD

**Issue by andyparsons** [c2pa-org/c2pa-org.github.io#12]
See screenshot.
<img width="495" alt="Screen Shot 2021-02-21 at 12 04 52 PM" src="https://user-images.githubusercontent.com/46599/108632470-1ccdab80-743d-11eb-9d11-cda9422e93bf.png">

**Comment by andyparsons** [comment]
Ideally the template would had a hamburger menu that takes care of this.

**Comment by lrosenthol** [comment]
Known issue for this theme with a submitted PR to fix - see https://github.com/theNewDynamic/gohugo-theme-ananke/issues/166

**Comment by andyparsons** [comment]
I see. Is there another theme that gets this right we could swap in? Or worth trying the forked Ananke? It's likely a good number of people will see this fist on their phones.

**Comment by dkozma** [comment]
@andyparsons We can probably close this with the new site launch being imminent.

**Comment by dkozma** [comment]
Fixed with #28.
