### ISSUE TITLE
Homepage header isn't mobile-ready

### ISSUE THREAD

**Issue by andyparsons** [c2pa-org/c2pa-org.github.io#13]
This is the same underlying issue as #12 but particularly acute here.
<img width="500" alt="Screen Shot 2021-02-21 at 12 06 43 PM" src="https://user-images.githubusercontent.com/46599/108632519-63bba100-743d-11eb-83ec-861ef0fcba67.png">

**Comment by lrosenthol** [comment]
This is really a combination of #9 and #12 

With the fix for #9, it's much better but the menus still fail as per #12.

**Comment by andyparsons** [comment]
Now that the launch dust has settled, we should address this issue. @dkozma @lrosenthol a couple of ideas:

1. use a smaller hero logo image at the browser breakpoint(s) this theme is using
2. Switch to a hero image and a smaller logo, perhaps only in the header

**Comment by dkozma** [comment]
@andyparsons We can probably close this with the new site launch being imminent.

**Comment by dkozma** [comment]
Fixed with #28.
