### ISSUE TITLE
C2PA hero image issues

### ISSUE THREAD

**Issue by andyparsons** [c2pa-org/c2pa-org.github.io#15]
- The homepage here image should use the C2PA logo font (Acumin). 
- Does the typeface need to be part of the image?

**Comment by lrosenthol** [comment]
It *IS* Acumin
![image](https://user-images.githubusercontent.com/5074741/108643907-9b950980-747a-11eb-9317-621fe9e17ab2.png)

And yes, because of the way the templates work, it needs to be part of the image

**Comment by lrosenthol** [comment]
I will note that because of our use of this font, the text in the SVG isn't text but outlines.

**Comment by andyparsons** [comment]
ok, closing this.
