### ISSUE TITLE
https://c2pa.org/public-draft/TrustModel.svg gives 404

### ISSUE THREAD

**Issue by mzeinstra** [c2pa-org/c2pa-org.github.io#59]
Chapter 13 'trust model' of the public draft refers to https://c2pa.org/public-draft/TrustModel.svg, which does not exist.

Steps to reproduce
go to: https://c2pa.org/public-draft/
go to chapter 13
See broken link

**Comment by lrosenthol** [comment]
The public draft is no longer the current version of the specification.  We are now at 1.0, which can be found at https://github.com/c2pa-org/specifications/
