### ISSUE TITLE
Some links not working

### ISSUE THREAD

**Issue by chrisn** [c2pa-org/c2pa-org.github.io#66]
The C2PA website at https://c2pa.org/ links to specs at https://c2pa.org/specifications/specifications/1.1/index.html, but on the 1.1 page, these links don't work:

* [Technical Specifications](https://c2pa.org/specifications/specifications/1.1/index.html#specs:C2PA_Specification.adoc)

* [Explainer](https://c2pa.org/specifications/specifications/1.1/index.html#1.0@explainer:Explainer.adoc)

* [Guidance for Implementers](https://c2pa.org/specifications/specifications/1.1/index.html#1.0@guidance:Guidance.adoc)

I notice there's a 1.2, so should c2pa.org link there instead?

Also, the right-hand side of the page has a drop-down list of the available versions, but if I use that to select 1.0, then the 1.2 entry disappears.

**Comment by qb20nh** [comment]
All versions of documents should correctly list all of the available versions.

**Comment by chrisn** [comment]
It looks like the document links are working now, but this issue still remains:

> the right-hand side of the page has a drop-down list of the available versions, but if I use that to select 1.0, then the 1.2 entry disappears.

**Comment by qb20nh** [comment]
I think the actual website structures and stuff are managed here: https://github.com/c2pa-org/c2pa-docs-ui

**Comment by lrosenthol** [comment]
yes the 1.2 release was a bit messed up - but the all other versions are good...Closing
