### ISSUE TITLE
FAQ header is taller than other pages

### ISSUE THREAD

**Issue by andyparsons** [c2pa-org/c2pa-org.github.io#8]
if you move between "about" and FAQ the header changes height.

**Comment by lrosenthol** [comment]
Yes, I know - it has to do with the fact that I have the description of FAQ there and so it enlarges the entire block.  I don't see an easy way to fix this.  How important??

@dkozma  any thoughts?

**Comment by andyparsons** [comment]
I think we can drop the description. FAQ is a common enough term.
